### ISSUE TITLE
About the 'environ.py' file

### ISSUE THREAD

**Issue by SwanKnightZJP** [M3DV/RibFrac-Challenge#3]
First, many thanks for publicing such an excellent dataset.

However, it seems that the ‘environ.py’ in the ‘ribfrac’ is empty. 
I wonder if you have adjusted the annotation of the label when you adjust the file structure.

I mean, the original label files seem to be marked according to the serial number of the fracture. How will they be evaluated? Do the labels need to be converted into specific category annotations according to the csv file?

Looking forward to your reply  (●'◡'●)

**Comment by kaimingkuang** [comment]
Sorry for the delay. This repo is still a work-in-progress. Originally we wanted this to be a pip-installable package but that's too much of a hassle. This repo will come out as a submission scorer. We are stilling finishing the final details on the evaluation code and will release it soon.
