### ISSUE TITLE
semantic error on the evaluation code

### ISSUE THREAD

**Issue by QixuanSun** [M3DV/RibFrac-Challenge#5]
There's a semantic error in "_interpolate_recall_at_fp".
Line 336-340: 
    fp_0 = fp_recall_less_fp["fp"].values[-1]
    fp_1 = fp_recall_more_fp["fp"].values[0]
    recall_0 = fp_recall_less_fp["recall"].values[-1]
    recall_1 = fp_recall_more_fp["recall"].values[0]

The correct code should be:
    fp_0 = fp_recall_less_fp["fp"].values[0]
    fp_1 = fp_recall_more_fp["fp"].values[-1]
    recall_0 = fp_recall_less_fp["recall"].values[0]
    recall_1 = fp_recall_more_fp["recall"].values[-1]

**Comment by kaimingkuang** [comment]
Thanks for spotting this bug. A new commit has been pushed and now the FP-recall data frame is sorted by FP in ascending order first before calculating key recall since this is easier.
