### ISSUE TITLE
Are there some cases with 22 or 26 ribs?

### ISSUE THREAD

**Issue by EricKani** [M3DV/RibFrac-Challenge#9]
~~~ question is the same as the title.
Thanks
Eric

**Comment by duducheng** [comment]
Hi,

Sorry, we didn’t collect the rib count information. The RibFrac challenge focuses on the fracture detection.

If you are interested in the rib segmentation, our MICCAI’21 study [RibSeg](https://github.com/M3DV/RibSeg) may be interesting for you.

Cheers,
Jiancheng

**Comment by EricKani** [comment]
Thanks！


| |
信工 刘蓬博
***@***.***
|

签名由 网易邮箱大师 定制

On 09/30/2021 14:18, Jiancheng wrote:

Hi,

Sorry, we didn’t collect the rib count information. The RibFrac challenge focuses on the fracture detection.

If you are interested in the rib segmentation, our MICCAI’21 study RibSeg may be interesting for you.

Cheers,
Jiancheng

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
